Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: 'ami-0b2ca94b5b49e0132'
      SubnetId: subnet-0575526893d7e2c91
      SecurityGroupIds:
        - sg-011cab7e75aa827a6
      # SecurityGroups :
      #   - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: myOumouInstance
